import { createAsyncThunk } from '@reduxjs/toolkit';
import axios from 'axios';

export const weekWeather = createAsyncThunk(
  'weekWeather/city1',
  // eslint-disable-next-line @typescript-eslint/require-await
  async ({ cityy }: { cityy?: string }, { rejectWithValue }) => {
    try {
      const response = {
        data: [
          {
            name: 'Moscow',
            local_names: {
              la: 'Moscua',
              fr: 'Moscou',
              cs: 'Moskva',
              ka: 'მოსკოვი',
              kk: 'Мәскеу',
              tl: 'Moscow',
              ky: 'Москва',
              yi: 'מאסקווע',
              fi: 'Moskova',
              kg: 'Moskva',
              feature_name: 'Moscow',
              gd: 'Moscobha',
              am: 'ሞስኮ',
              yo: 'Mọsko',
              da: 'Moskva',
              fa: 'مسکو',
              bs: 'Moskva',
              et: 'Moskva',
              ht: 'Moskou',
              gn: 'Mosku',
              oc: 'Moscòu',
              es: 'Moscú',
              ab: 'Москва',
              br: 'Moskov',
              wa: 'Moscou',
              pt: 'Moscou',
              tt: 'Мәскәү',
              ch: 'Moscow',
              te: 'మాస్కో',
              su: 'Moskwa',
              mt: 'Moska',
              so: 'Moskow',
              hi: 'मास्को',
              sg: 'Moscow',
              ss: 'Moscow',
              st: 'Moscow',
              bi: 'Moskow',
              ce: 'Москох',
              ku: 'Moskow',
              ta: 'மாஸ்கோ',
              sh: 'Moskva',
              no: 'Moskva',
              sv: 'Moskva',
              gl: 'Moscova - Москва',
              dv: 'މޮސްކޯ',
              li: 'Moskou',
              ml: 'മോസ്കോ',
              os: 'Мæскуы',
              ln: 'Moskú',
              ba: 'Мәскәү',
              mk: 'Москва',
              io: 'Moskva',
              wo: 'Mosku',
              jv: 'Moskwa',
              sw: 'Moscow',
              dz: 'མོསི་ཀོ',
              de: 'Moskau',
              sq: 'Moska',
              ie: 'Moskwa',
              mn: 'Москва',
              mg: 'Moskva',
              af: 'Moskou',
              id: 'Moskwa',
              nl: 'Moskou',
              ms: 'Moscow',
              sr: 'Москва',
              kn: 'ಮಾಸ್ಕೋ',
              az: 'Moskva',
              sk: 'Moskva',
              he: 'מוסקווה',
              ug: 'Moskwa',
              bg: 'Москва',
              en: 'Moscow',
              it: 'Mosca',
              tr: 'Moskova',
              nn: 'Moskva',
              kl: 'Moskva',
              ko: '모스크바',
              za: 'Moscow',
              an: 'Moscú',
              eu: 'Mosku',
              vi: 'Mát-xcơ-va',
              cv: 'Мускав',
              sm: 'Moscow',
              nb: 'Moskva',
              ay: 'Mosku',
              lt: 'Maskva',
              ps: 'مسکو',
              pl: 'Moskwa',
              cu: 'Москъва',
              bn: 'মস্কো',
              hy: 'Մոսկվա',
              mr: 'मॉस्को',
              vo: 'Moskva',
              sl: 'Moskva',
              ru: 'Москва',
              ty: 'Moscou',
              lv: 'Maskava',
              kw: 'Moskva',
              ascii: 'Moscow',
              qu: 'Moskwa',
              uk: 'Москва',
              ak: 'Moscow',
              fo: 'Moskva',
              is: 'Moskva',
              uz: 'Moskva',
              tk: 'Moskwa',
              na: 'Moscow',
              ro: 'Moscova',
              hr: 'Moskva',
              ur: 'ماسکو',
              hu: 'Moszkva',
              bo: 'མོ་སི་ཁོ།',
              sc: 'Mosca',
              lg: 'Moosko',
              co: 'Moscù',
              ca: 'Moscou',
              iu: 'ᒨᔅᑯ',
              av: 'Москва',
              tg: 'Маскав',
              ga: 'Moscó',
              mi: 'Mohikau',
              ja: 'モスクワ',
              el: 'Μόσχα',
              ia: 'Moscova',
              eo: 'Moskvo',
              cy: 'Moscfa',
              be: 'Масква',
              fy: 'Moskou',
              ar: 'موسكو',
              zu: 'IMoskwa',
              th: 'มอสโก',
              zh: '莫斯科',
              my: 'မော်စကိုမြို့',
              se: 'Moskva',
              gv: 'Moscow',
              kv: 'Мӧскуа',
            },
            lat: 55.750_446_1,
            lon: 37.617_494_3,
            country: 'RU',
            state: 'Moscow',
          },
        ],
      };
      // await axios.get(
      //   `https://api.openweathermap.org/geo/1.0/direct?q=${cityy}&appid=4ccd5856fcef61a049f819bbe02ae1cc`
      // );
      // const getСoordinates = await axios.get(
      //   `https://api.openweathermap.org/data/2.5/onecall?lat=${response.data[0].lat}&lon=${response.data[0].lon}&lang=ru&appid=4ccd5856fcef61a049f819bbe02ae1cc`
      // );
      const getСoordinates = {
        data: {
          lat: 55.7504,
          lon: 37.6175,
          timezone: 'Europe/Moscow',
          timezone_offset: 10_800,
          current: {
            dt: 1_653_754_083,
            sunrise: 1_653_699_494,
            sunset: 1_653_760_540,
            temp: 285.39,
            feels_like: 284.65,
            pressure: 1003,
            humidity: 76,
            dew_point: 281.29,
            uvi: 0.08,
            clouds: 100,
            visibility: 10_000,
            wind_speed: 4.56,
            wind_deg: 251,
            wind_gust: 9.48,
            weather: [
              { id: 804, main: 'Clouds', description: 'пасмурно', icon: '04d' },
            ],
          },
          minutely: [
            { dt: 1_653_754_140, precipitation: 0 },
            { dt: 1_653_754_200, precipitation: 0 },
            { dt: 1_653_754_260, precipitation: 0 },
            { dt: 1_653_754_320, precipitation: 0 },
            { dt: 1_653_754_380, precipitation: 0 },
            { dt: 1_653_754_440, precipitation: 0 },
            { dt: 1_653_754_500, precipitation: 0 },
            { dt: 1_653_754_560, precipitation: 0 },
            { dt: 1_653_754_620, precipitation: 0 },
            { dt: 1_653_754_680, precipitation: 0 },
            { dt: 1_653_754_740, precipitation: 0 },
            { dt: 1_653_754_800, precipitation: 0 },
            { dt: 1_653_754_860, precipitation: 0 },
            { dt: 1_653_754_920, precipitation: 0 },
            { dt: 1_653_754_980, precipitation: 0 },
            { dt: 1_653_755_040, precipitation: 0 },
            { dt: 1_653_755_100, precipitation: 0 },
            { dt: 1_653_755_160, precipitation: 0 },
            { dt: 1_653_755_220, precipitation: 0 },
            { dt: 1_653_755_280, precipitation: 0 },
            { dt: 1_653_755_340, precipitation: 0 },
            { dt: 1_653_755_400, precipitation: 0 },
            { dt: 1_653_755_460, precipitation: 0 },
            { dt: 1_653_755_520, precipitation: 0 },
            { dt: 1_653_755_580, precipitation: 0 },
            { dt: 1_653_755_640, precipitation: 0 },
            { dt: 1_653_755_700, precipitation: 0 },
            { dt: 1_653_755_760, precipitation: 0 },
            { dt: 1_653_755_820, precipitation: 0 },
            { dt: 1_653_755_880, precipitation: 0 },
            { dt: 1_653_755_940, precipitation: 0 },
            { dt: 1_653_756_000, precipitation: 0 },
            { dt: 1_653_756_060, precipitation: 0 },
            { dt: 1_653_756_120, precipitation: 0 },
            { dt: 1_653_756_180, precipitation: 0 },
            { dt: 1_653_756_240, precipitation: 0 },
            { dt: 1_653_756_300, precipitation: 0 },
            { dt: 1_653_756_360, precipitation: 0 },
            { dt: 1_653_756_420, precipitation: 0 },
            { dt: 1_653_756_480, precipitation: 0 },
            { dt: 1_653_756_540, precipitation: 0 },
            { dt: 1_653_756_600, precipitation: 0 },
            { dt: 1_653_756_660, precipitation: 0 },
            { dt: 1_653_756_720, precipitation: 0 },
            { dt: 1_653_756_780, precipitation: 0 },
            { dt: 1_653_756_840, precipitation: 0 },
            { dt: 1_653_756_900, precipitation: 0 },
            { dt: 1_653_756_960, precipitation: 0 },
            { dt: 1_653_757_020, precipitation: 0 },
            { dt: 1_653_757_080, precipitation: 0 },
            { dt: 1_653_757_140, precipitation: 0 },
            { dt: 1_653_757_200, precipitation: 0 },
            { dt: 1_653_757_260, precipitation: 0 },
            { dt: 1_653_757_320, precipitation: 0 },
            { dt: 1_653_757_380, precipitation: 0 },
            { dt: 1_653_757_440, precipitation: 0 },
            { dt: 1_653_757_500, precipitation: 0 },
            { dt: 1_653_757_560, precipitation: 0 },
            { dt: 1_653_757_620, precipitation: 0 },
            { dt: 1_653_757_680, precipitation: 0 },
            { dt: 1_653_757_740, precipitation: 0 },
          ],
          hourly: [
            {
              dt: 1_653_753_600,
              temp: 285.39,
              feels_like: 284.65,
              pressure: 1003,
              humidity: 76,
              dew_point: 281.29,
              uvi: 0.08,
              clouds: 100,
              visibility: 10_000,
              wind_speed: 4.56,
              wind_deg: 251,
              wind_gust: 9.48,
              weather: [
                {
                  id: 804,
                  main: 'Clouds',
                  description: 'пасмурно',
                  icon: '04d',
                },
              ],
              pop: 0.72,
            },
            {
              dt: 1_653_757_200,
              temp: 284.95,
              feels_like: 284.17,
              pressure: 1003,
              humidity: 76,
              dew_point: 280.86,
              uvi: 0.02,
              clouds: 100,
              visibility: 10_000,
              wind_speed: 4.7,
              wind_deg: 254,
              wind_gust: 10.51,
              weather: [
                {
                  id: 804,
                  main: 'Clouds',
                  description: 'пасмурно',
                  icon: '04d',
                },
              ],
              pop: 0.66,
            },
            {
              dt: 1_653_760_800,
              temp: 284.13,
              feels_like: 283.32,
              pressure: 1003,
              humidity: 78,
              dew_point: 280.45,
              uvi: 0,
              clouds: 98,
              visibility: 10_000,
              wind_speed: 4.3,
              wind_deg: 249,
              wind_gust: 11.11,
              weather: [
                {
                  id: 804,
                  main: 'Clouds',
                  description: 'пасмурно',
                  icon: '04n',
                },
              ],
              pop: 0.58,
            },
            {
              dt: 1_653_764_400,
              temp: 283.11,
              feels_like: 281.15,
              pressure: 1004,
              humidity: 80,
              dew_point: 279.82,
              uvi: 0,
              clouds: 55,
              visibility: 10_000,
              wind_speed: 3.9,
              wind_deg: 244,
              wind_gust: 10.81,
              weather: [
                {
                  id: 803,
                  main: 'Clouds',
                  // eslint-disable-next-line sonarjs/no-duplicate-string
                  description: 'облачно с прояснениями',
                  icon: '04n',
                },
              ],
              pop: 0,
            },
            {
              dt: 1_653_768_000,
              temp: 281.8,
              feels_like: 279.65,
              pressure: 1005,
              humidity: 83,
              dew_point: 279.08,
              uvi: 0,
              clouds: 32,
              visibility: 10_000,
              wind_speed: 3.69,
              wind_deg: 235,
              wind_gust: 10,
              weather: [
                {
                  id: 802,
                  main: 'Clouds',
                  // eslint-disable-next-line sonarjs/no-duplicate-string
                  description: 'переменная облачность',
                  icon: '03n',
                },
              ],
              pop: 0,
            },
            {
              dt: 1_653_771_600,
              temp: 280.32,
              feels_like: 277.77,
              pressure: 1006,
              humidity: 87,
              dew_point: 278.13,
              uvi: 0,
              clouds: 13,
              visibility: 10_000,
              wind_speed: 3.83,
              wind_deg: 231,
              wind_gust: 10.17,
              weather: [
                {
                  id: 801,
                  main: 'Clouds',
                  description: 'небольшая облачность',
                  icon: '02n',
                },
              ],
              pop: 0,
            },
            {
              dt: 1_653_775_200,
              temp: 279.97,
              feels_like: 277.67,
              pressure: 1006,
              humidity: 88,
              dew_point: 278.08,
              uvi: 0,
              clouds: 12,
              visibility: 10_000,
              wind_speed: 3.27,
              wind_deg: 239,
              wind_gust: 9.97,
              weather: [
                {
                  id: 801,
                  main: 'Clouds',
                  description: 'небольшая облачность',
                  icon: '02n',
                },
              ],
              pop: 0,
            },
            {
              dt: 1_653_778_800,
              temp: 279.56,
              feels_like: 277.22,
              pressure: 1006,
              humidity: 90,
              dew_point: 278.02,
              uvi: 0,
              clouds: 10,
              visibility: 10_000,
              wind_speed: 3.2,
              wind_deg: 231,
              wind_gust: 8.93,
              weather: [
                { id: 800, main: 'Clear', description: 'ясно', icon: '01n' },
              ],
              pop: 0,
            },
            {
              dt: 1_653_782_400,
              temp: 279.16,
              feels_like: 276.65,
              pressure: 1007,
              humidity: 92,
              dew_point: 277.94,
              uvi: 0,
              clouds: 9,
              visibility: 10_000,
              wind_speed: 3.32,
              wind_deg: 228,
              wind_gust: 9.26,
              weather: [
                { id: 800, main: 'Clear', description: 'ясно', icon: '01n' },
              ],
              pop: 0,
            },
            {
              dt: 1_653_786_000,
              temp: 279.04,
              feels_like: 276.41,
              pressure: 1007,
              humidity: 92,
              dew_point: 277.78,
              uvi: 0,
              clouds: 70,
              visibility: 10_000,
              wind_speed: 3.47,
              wind_deg: 228,
              wind_gust: 9.76,
              weather: [
                {
                  id: 803,
                  main: 'Clouds',
                  description: 'облачно с прояснениями',
                  icon: '04d',
                },
              ],
              pop: 0,
            },
            {
              dt: 1_653_789_600,
              temp: 279.38,
              feels_like: 276.88,
              pressure: 1007,
              humidity: 91,
              dew_point: 277.97,
              uvi: 0.08,
              clouds: 85,
              visibility: 10_000,
              wind_speed: 3.39,
              wind_deg: 226,
              wind_gust: 9.37,
              weather: [
                {
                  id: 804,
                  main: 'Clouds',
                  description: 'пасмурно',
                  icon: '04d',
                },
              ],
              pop: 0,
            },
            {
              dt: 1_653_793_200,
              temp: 280.45,
              feels_like: 277.92,
              pressure: 1008,
              humidity: 87,
              dew_point: 278.4,
              uvi: 0.25,
              clouds: 90,
              visibility: 10_000,
              wind_speed: 3.83,
              wind_deg: 235,
              wind_gust: 10.51,
              weather: [
                {
                  id: 804,
                  main: 'Clouds',
                  description: 'пасмурно',
                  icon: '04d',
                },
              ],
              pop: 0,
            },
            {
              dt: 1_653_796_800,
              temp: 281.84,
              feels_like: 279.3,
              pressure: 1008,
              humidity: 81,
              dew_point: 278.63,
              uvi: 0.49,
              clouds: 93,
              visibility: 10_000,
              wind_speed: 4.53,
              wind_deg: 237,
              wind_gust: 9.95,
              weather: [
                {
                  id: 804,
                  main: 'Clouds',
                  description: 'пасмурно',
                  icon: '04d',
                },
              ],
              pop: 0,
            },
            {
              dt: 1_653_800_400,
              temp: 283.46,
              feels_like: 282.4,
              pressure: 1008,
              humidity: 71,
              dew_point: 278.44,
              uvi: 0.93,
              clouds: 92,
              visibility: 10_000,
              wind_speed: 4.76,
              wind_deg: 239,
              wind_gust: 7.85,
              weather: [
                {
                  id: 804,
                  main: 'Clouds',
                  description: 'пасмурно',
                  icon: '04d',
                },
              ],
              pop: 0,
            },
            {
              dt: 1_653_804_000,
              temp: 285.17,
              feels_like: 284.05,
              pressure: 1009,
              humidity: 62,
              dew_point: 278,
              uvi: 1.52,
              clouds: 82,
              visibility: 10_000,
              wind_speed: 4.82,
              wind_deg: 248,
              wind_gust: 6.97,
              weather: [
                {
                  id: 803,
                  main: 'Clouds',
                  description: 'облачно с прояснениями',
                  icon: '04d',
                },
              ],
              pop: 0,
            },
            {
              dt: 1_653_807_600,
              temp: 285.94,
              feels_like: 284.79,
              pressure: 1009,
              humidity: 58,
              dew_point: 278,
              uvi: 2.07,
              clouds: 26,
              visibility: 10_000,
              wind_speed: 5.28,
              wind_deg: 251,
              wind_gust: 6.96,
              weather: [
                {
                  id: 500,
                  main: 'Rain',
                  // eslint-disable-next-line sonarjs/no-duplicate-string
                  description: 'небольшой дождь',
                  icon: '10d',
                },
              ],
              pop: 1,
              rain: { '1h': 0.28 },
            },
            {
              dt: 1_653_811_200,
              temp: 286.7,
              feels_like: 285.55,
              pressure: 1010,
              humidity: 55,
              dew_point: 277.85,
              uvi: 2.58,
              clouds: 34,
              visibility: 10_000,
              wind_speed: 5.56,
              wind_deg: 249,
              wind_gust: 7.26,
              weather: [
                {
                  id: 500,
                  main: 'Rain',
                  description: 'небольшой дождь',
                  icon: '10d',
                },
              ],
              pop: 1,
              rain: { '1h': 0.4 },
            },
            {
              dt: 1_653_814_800,
              temp: 287.61,
              feels_like: 286.39,
              pressure: 1010,
              humidity: 49,
              dew_point: 276.88,
              uvi: 2.88,
              clouds: 38,
              visibility: 10_000,
              wind_speed: 5.8,
              wind_deg: 240,
              wind_gust: 7.43,
              weather: [
                {
                  id: 500,
                  main: 'Rain',
                  description: 'небольшой дождь',
                  icon: '10d',
                },
              ],
              pop: 1,
              rain: { '1h': 0.25 },
            },
            {
              dt: 1_653_818_400,
              temp: 288.08,
              feels_like: 286.86,
              pressure: 1010,
              humidity: 47,
              dew_point: 276.75,
              uvi: 3.8,
              clouds: 41,
              visibility: 10_000,
              wind_speed: 6.41,
              wind_deg: 235,
              wind_gust: 7.67,
              weather: [
                {
                  id: 500,
                  main: 'Rain',
                  description: 'небольшой дождь',
                  icon: '10d',
                },
              ],
              pop: 0.96,
              rain: { '1h': 0.16 },
            },
            {
              dt: 1_653_822_000,
              temp: 288.57,
              feels_like: 287.26,
              pressure: 1011,
              humidity: 42,
              dew_point: 275.8,
              uvi: 3.41,
              clouds: 47,
              visibility: 10_000,
              wind_speed: 5.86,
              wind_deg: 245,
              wind_gust: 7.88,
              weather: [
                {
                  id: 802,
                  main: 'Clouds',
                  description: 'переменная облачность',
                  icon: '03d',
                },
              ],
              pop: 0.88,
            },
            {
              dt: 1_653_825_600,
              temp: 289.33,
              feels_like: 288,
              pressure: 1011,
              humidity: 38,
              dew_point: 275.07,
              uvi: 2.73,
              clouds: 50,
              visibility: 10_000,
              wind_speed: 4.97,
              wind_deg: 259,
              wind_gust: 8.31,
              weather: [
                {
                  id: 802,
                  main: 'Clouds',
                  description: 'переменная облачность',
                  icon: '03d',
                },
              ],
              pop: 0.86,
            },
            {
              dt: 1_653_829_200,
              temp: 289.31,
              feels_like: 288,
              pressure: 1011,
              humidity: 39,
              dew_point: 275.5,
              uvi: 2.12,
              clouds: 82,
              visibility: 10_000,
              wind_speed: 5.83,
              wind_deg: 241,
              wind_gust: 7.8,
              weather: [
                {
                  id: 803,
                  main: 'Clouds',
                  description: 'облачно с прояснениями',
                  icon: '04d',
                },
              ],
              pop: 0.6,
            },
            {
              dt: 1_653_832_800,
              temp: 288.19,
              feels_like: 286.92,
              pressure: 1012,
              humidity: 45,
              dew_point: 276.29,
              uvi: 1.3,
              clouds: 90,
              visibility: 10_000,
              wind_speed: 5.33,
              wind_deg: 249,
              wind_gust: 7.75,
              weather: [
                {
                  id: 804,
                  main: 'Clouds',
                  description: 'пасмурно',
                  icon: '04d',
                },
              ],
              pop: 0.56,
            },
            {
              dt: 1_653_836_400,
              temp: 288.54,
              feels_like: 287.26,
              pressure: 1012,
              humidity: 43,
              dew_point: 276.04,
              uvi: 0.68,
              clouds: 67,
              visibility: 10_000,
              wind_speed: 5.06,
              wind_deg: 260,
              wind_gust: 7.45,
              weather: [
                {
                  id: 803,
                  main: 'Clouds',
                  description: 'облачно с прояснениями',
                  icon: '04d',
                },
              ],
              pop: 0.5,
            },
            {
              dt: 1_653_840_000,
              temp: 287.98,
              feels_like: 286.75,
              pressure: 1013,
              humidity: 47,
              dew_point: 276.85,
              uvi: 0.32,
              clouds: 53,
              visibility: 10_000,
              wind_speed: 3.78,
              wind_deg: 263,
              wind_gust: 7.06,
              weather: [
                {
                  id: 803,
                  main: 'Clouds',
                  description: 'облачно с прояснениями',
                  icon: '04d',
                },
              ],
              pop: 0.46,
            },
            {
              dt: 1_653_843_600,
              temp: 286.53,
              feels_like: 285.33,
              pressure: 1013,
              humidity: 54,
              dew_point: 277.39,
              uvi: 0.1,
              clouds: 44,
              visibility: 10_000,
              wind_speed: 3.21,
              wind_deg: 258,
              wind_gust: 6.84,
              weather: [
                {
                  id: 802,
                  main: 'Clouds',
                  description: 'переменная облачность',
                  icon: '03d',
                },
              ],
              pop: 0.36,
            },
            {
              dt: 1_653_847_200,
              temp: 284.86,
              feels_like: 283.71,
              pressure: 1014,
              humidity: 62,
              dew_point: 277.7,
              uvi: 0,
              clouds: 37,
              visibility: 10_000,
              wind_speed: 2.39,
              wind_deg: 246,
              wind_gust: 5.56,
              weather: [
                {
                  id: 802,
                  main: 'Clouds',
                  description: 'переменная облачность',
                  icon: '03n',
                },
              ],
              pop: 0.32,
            },
            {
              dt: 1_653_850_800,
              temp: 283.93,
              feels_like: 282.87,
              pressure: 1015,
              humidity: 69,
              dew_point: 278.25,
              uvi: 0,
              clouds: 0,
              visibility: 10_000,
              wind_speed: 2.46,
              wind_deg: 233,
              wind_gust: 6.15,
              weather: [
                { id: 800, main: 'Clear', description: 'ясно', icon: '01n' },
              ],
              pop: 0,
            },
            {
              dt: 1_653_854_400,
              temp: 283.15,
              feels_like: 282.02,
              pressure: 1016,
              humidity: 73,
              dew_point: 278.43,
              uvi: 0,
              clouds: 0,
              visibility: 10_000,
              wind_speed: 2.43,
              wind_deg: 239,
              wind_gust: 6.1,
              weather: [
                { id: 800, main: 'Clear', description: 'ясно', icon: '01n' },
              ],
              pop: 0,
            },
            {
              dt: 1_653_858_000,
              temp: 282.47,
              feels_like: 281.15,
              pressure: 1016,
              humidity: 76,
              dew_point: 278.5,
              uvi: 0,
              clouds: 0,
              visibility: 10_000,
              wind_speed: 2.53,
              wind_deg: 250,
              wind_gust: 6.57,
              weather: [
                { id: 800, main: 'Clear', description: 'ясно', icon: '01n' },
              ],
              pop: 0,
            },
            {
              dt: 1_653_861_600,
              temp: 281.94,
              feels_like: 280.59,
              pressure: 1017,
              humidity: 80,
              dew_point: 278.48,
              uvi: 0,
              clouds: 0,
              visibility: 10_000,
              wind_speed: 2.43,
              wind_deg: 244,
              wind_gust: 5.95,
              weather: [
                { id: 800, main: 'Clear', description: 'ясно', icon: '01n' },
              ],
              pop: 0,
            },
            {
              dt: 1_653_865_200,
              temp: 281.41,
              feels_like: 280.02,
              pressure: 1018,
              humidity: 82,
              dew_point: 278.53,
              uvi: 0,
              clouds: 0,
              visibility: 10_000,
              wind_speed: 2.36,
              wind_deg: 248,
              wind_gust: 5.58,
              weather: [
                { id: 800, main: 'Clear', description: 'ясно', icon: '01n' },
              ],
              pop: 0,
            },
            {
              dt: 1_653_868_800,
              temp: 281.01,
              feels_like: 279.83,
              pressure: 1018,
              humidity: 84,
              dew_point: 278.48,
              uvi: 0,
              clouds: 0,
              visibility: 10_000,
              wind_speed: 2.02,
              wind_deg: 251,
              wind_gust: 4.44,
              weather: [
                { id: 800, main: 'Clear', description: 'ясно', icon: '01n' },
              ],
              pop: 0,
            },
            {
              dt: 1_653_872_400,
              temp: 280.62,
              feels_like: 279.41,
              pressure: 1018,
              humidity: 86,
              dew_point: 278.33,
              uvi: 0,
              clouds: 32,
              visibility: 10_000,
              wind_speed: 1.98,
              wind_deg: 241,
              wind_gust: 3.68,
              weather: [
                {
                  id: 802,
                  main: 'Clouds',
                  description: 'переменная облачность',
                  icon: '03d',
                },
              ],
              pop: 0,
            },
            {
              dt: 1_653_876_000,
              temp: 280.84,
              feels_like: 280.04,
              pressure: 1019,
              humidity: 85,
              dew_point: 278.33,
              uvi: 0.11,
              clouds: 54,
              visibility: 10_000,
              wind_speed: 1.61,
              wind_deg: 243,
              wind_gust: 2.98,
              weather: [
                {
                  id: 803,
                  main: 'Clouds',
                  description: 'облачно с прояснениями',
                  icon: '04d',
                },
              ],
              pop: 0,
            },
            {
              dt: 1_653_879_600,
              temp: 282.03,
              feels_like: 281.26,
              pressure: 1019,
              humidity: 78,
              dew_point: 278.46,
              uvi: 0.34,
              clouds: 69,
              visibility: 10_000,
              wind_speed: 1.75,
              wind_deg: 244,
              wind_gust: 3.02,
              weather: [
                {
                  id: 803,
                  main: 'Clouds',
                  description: 'облачно с прояснениями',
                  icon: '04d',
                },
              ],
              pop: 0,
            },
            {
              dt: 1_653_883_200,
              temp: 283.81,
              feels_like: 282.76,
              pressure: 1020,
              humidity: 70,
              dew_point: 278.57,
              uvi: 0.83,
              clouds: 57,
              visibility: 10_000,
              wind_speed: 1.7,
              wind_deg: 225,
              wind_gust: 2.46,
              weather: [
                {
                  id: 803,
                  main: 'Clouds',
                  description: 'облачно с прояснениями',
                  icon: '04d',
                },
              ],
              pop: 0,
            },
            {
              dt: 1_653_886_800,
              temp: 285.51,
              feels_like: 284.47,
              pressure: 1020,
              humidity: 64,
              dew_point: 278.84,
              uvi: 1.6,
              clouds: 49,
              visibility: 10_000,
              wind_speed: 2.32,
              wind_deg: 208,
              wind_gust: 3.16,
              weather: [
                {
                  id: 802,
                  main: 'Clouds',
                  description: 'переменная облачность',
                  icon: '03d',
                },
              ],
              pop: 0,
            },
            {
              dt: 1_653_890_400,
              temp: 287.06,
              feels_like: 286.02,
              pressure: 1020,
              humidity: 58,
              dew_point: 278.89,
              uvi: 2.62,
              clouds: 43,
              visibility: 10_000,
              wind_speed: 2.28,
              wind_deg: 199,
              wind_gust: 3.06,
              weather: [
                {
                  id: 802,
                  main: 'Clouds',
                  description: 'переменная облачность',
                  icon: '03d',
                },
              ],
              pop: 0,
            },
            {
              dt: 1_653_894_000,
              temp: 288.64,
              feels_like: 287.55,
              pressure: 1020,
              humidity: 50,
              dew_point: 278.33,
              uvi: 3.79,
              clouds: 10,
              visibility: 10_000,
              wind_speed: 2.41,
              wind_deg: 184,
              wind_gust: 3.05,
              weather: [
                { id: 800, main: 'Clear', description: 'ясно', icon: '01d' },
              ],
              pop: 0,
            },
            {
              dt: 1_653_897_600,
              temp: 289.81,
              feels_like: 288.71,
              pressure: 1020,
              humidity: 45,
              dew_point: 277.83,
              uvi: 4.74,
              clouds: 10,
              visibility: 10_000,
              wind_speed: 2.92,
              wind_deg: 180,
              wind_gust: 3.61,
              weather: [
                { id: 800, main: 'Clear', description: 'ясно', icon: '01d' },
              ],
              pop: 0,
            },
            {
              dt: 1_653_901_200,
              temp: 290.76,
              feels_like: 289.67,
              pressure: 1020,
              humidity: 42,
              dew_point: 277.63,
              uvi: 5.29,
              clouds: 9,
              visibility: 10_000,
              wind_speed: 3.16,
              wind_deg: 174,
              wind_gust: 3.89,
              weather: [
                { id: 800, main: 'Clear', description: 'ясно', icon: '01d' },
              ],
              pop: 0,
            },
            {
              dt: 1_653_904_800,
              temp: 291.45,
              feels_like: 290.38,
              pressure: 1020,
              humidity: 40,
              dew_point: 277.69,
              uvi: 4.87,
              clouds: 32,
              visibility: 10_000,
              wind_speed: 3.44,
              wind_deg: 167,
              wind_gust: 4.05,
              weather: [
                {
                  id: 802,
                  main: 'Clouds',
                  description: 'переменная облачность',
                  icon: '03d',
                },
              ],
              pop: 0,
            },
            {
              dt: 1_653_908_400,
              temp: 291.83,
              feels_like: 290.8,
              pressure: 1019,
              humidity: 40,
              dew_point: 277.91,
              uvi: 4.36,
              clouds: 46,
              visibility: 10_000,
              wind_speed: 3.73,
              wind_deg: 161,
              wind_gust: 4.4,
              weather: [
                {
                  id: 802,
                  main: 'Clouds',
                  description: 'переменная облачность',
                  icon: '03d',
                },
              ],
              pop: 0,
            },
            {
              dt: 1_653_912_000,
              temp: 291.91,
              feels_like: 290.89,
              pressure: 1019,
              humidity: 40,
              dew_point: 278.11,
              uvi: 3.49,
              clouds: 55,
              visibility: 10_000,
              wind_speed: 4.25,
              wind_deg: 165,
              wind_gust: 5.08,
              weather: [
                {
                  id: 803,
                  main: 'Clouds',
                  description: 'облачно с прояснениями',
                  icon: '04d',
                },
              ],
              pop: 0,
            },
            {
              dt: 1_653_915_600,
              temp: 291.3,
              feels_like: 290.29,
              pressure: 1019,
              humidity: 43,
              dew_point: 278.71,
              uvi: 1.52,
              clouds: 100,
              visibility: 10_000,
              wind_speed: 4.05,
              wind_deg: 161,
              wind_gust: 5.39,
              weather: [
                {
                  id: 804,
                  main: 'Clouds',
                  description: 'пасмурно',
                  icon: '04d',
                },
              ],
              pop: 0.02,
            },
            {
              dt: 1_653_919_200,
              temp: 289.97,
              feels_like: 289.14,
              pressure: 1019,
              humidity: 55,
              dew_point: 280.82,
              uvi: 0.93,
              clouds: 100,
              visibility: 10_000,
              wind_speed: 3.33,
              wind_deg: 173,
              wind_gust: 5.56,
              weather: [
                {
                  id: 804,
                  main: 'Clouds',
                  description: 'пасмурно',
                  icon: '04d',
                },
              ],
              pop: 0.28,
            },
            {
              dt: 1_653_922_800,
              temp: 287.18,
              feels_like: 286.75,
              pressure: 1020,
              humidity: 81,
              dew_point: 283.93,
              uvi: 0.48,
              clouds: 100,
              visibility: 10_000,
              wind_speed: 3.35,
              wind_deg: 201,
              wind_gust: 6.22,
              weather: [
                {
                  id: 500,
                  main: 'Rain',
                  description: 'небольшой дождь',
                  icon: '10d',
                },
              ],
              pop: 0.6,
              rain: { '1h': 0.9 },
            },
          ],
          daily: [
            {
              dt: 1_653_728_400,
              sunrise: 1_653_699_494,
              sunset: 1_653_760_540,
              moonrise: 1_653_696_900,
              moonset: 1_653_752_760,
              moon_phase: 0.93,
              temp: {
                day: 286.36,
                min: 279.77,
                max: 286.36,
                night: 281.8,
                eve: 284.87,
                morn: 281.37,
              },
              feels_like: {
                day: 285.25,
                night: 279.65,
                eve: 284.11,
                morn: 280.58,
              },
              pressure: 999,
              humidity: 58,
              dew_point: 278.25,
              wind_speed: 6.04,
              wind_deg: 235,
              wind_gust: 11.11,
              weather: [
                {
                  id: 500,
                  main: 'Rain',
                  description: 'небольшой дождь',
                  icon: '10d',
                },
              ],
              clouds: 100,
              pop: 0.92,
              rain: 1.36,
              uvi: 3.26,
            },
            {
              dt: 1_653_814_800,
              sunrise: 1_653_785_820,
              sunset: 1_653_847_029,
              moonrise: 1_653_784_020,
              moonset: 1_653_843_900,
              moon_phase: 0.97,
              temp: {
                day: 287.61,
                min: 279.04,
                max: 289.33,
                night: 283.15,
                eve: 288.54,
                morn: 280.45,
              },
              feels_like: {
                day: 286.39,
                night: 282.02,
                eve: 287.26,
                morn: 277.92,
              },
              pressure: 1010,
              humidity: 49,
              dew_point: 276.88,
              wind_speed: 6.41,
              wind_deg: 235,
              wind_gust: 10.51,
              weather: [
                {
                  id: 500,
                  main: 'Rain',
                  description: 'небольшой дождь',
                  icon: '10d',
                },
              ],
              clouds: 38,
              pop: 1,
              rain: 1.09,
              uvi: 3.8,
            },
            {
              dt: 1_653_901_200,
              sunrise: 1_653_872_149,
              sunset: 1_653_933_517,
              moonrise: 1_653_871_320,
              moonset: 1_653_934_920,
              moon_phase: 0,
              temp: {
                day: 290.76,
                min: 280.62,
                max: 291.91,
                night: 285.74,
                eve: 287.18,
                morn: 282.03,
              },
              feels_like: {
                day: 289.67,
                night: 285.38,
                eve: 286.75,
                morn: 281.26,
              },
              pressure: 1020,
              humidity: 42,
              dew_point: 277.63,
              wind_speed: 4.83,
              wind_deg: 116,
              wind_gust: 11.86,
              weather: [
                {
                  id: 500,
                  main: 'Rain',
                  description: 'небольшой дождь',
                  icon: '10d',
                },
              ],
              clouds: 9,
              pop: 0.86,
              rain: 1.93,
              uvi: 5.29,
            },
            {
              dt: 1_653_987_600,
              sunrise: 1_653_958_481,
              sunset: 1_654_020_001,
              moonrise: 1_653_958_980,
              moonset: 1_654_025_580,
              moon_phase: 0.03,
              temp: {
                day: 288.34,
                min: 285.31,
                max: 290.58,
                night: 288.23,
                eve: 290.58,
                morn: 285.93,
              },
              feels_like: {
                day: 288.4,
                night: 288.27,
                eve: 290.7,
                morn: 285.82,
              },
              pressure: 1018,
              humidity: 95,
              dew_point: 287.38,
              wind_speed: 5.93,
              wind_deg: 120,
              wind_gust: 13.27,
              weather: [
                { id: 501, main: 'Rain', description: 'дождь', icon: '10d' },
              ],
              clouds: 100,
              pop: 0.94,
              rain: 9.56,
              uvi: 0.69,
            },
            {
              dt: 1_654_074_000,
              sunrise: 1_654_044_816,
              sunset: 1_654_106_484,
              moonrise: 1_654_047_300,
              moonset: 1_654_115_520,
              moon_phase: 0.06,
              temp: {
                day: 293.27,
                min: 287.14,
                max: 295.35,
                night: 290.14,
                eve: 293.15,
                morn: 287.68,
              },
              feels_like: {
                day: 293.11,
                night: 289.75,
                eve: 292.8,
                morn: 287.77,
              },
              pressure: 1018,
              humidity: 68,
              dew_point: 287.01,
              wind_speed: 3.25,
              wind_deg: 103,
              wind_gust: 7.85,
              weather: [
                { id: 501, main: 'Rain', description: 'дождь', icon: '10d' },
              ],
              clouds: 75,
              pop: 1,
              rain: 10.17,
              uvi: 5.58,
            },
            {
              dt: 1_654_160_400,
              sunrise: 1_654_131_154,
              sunset: 1_654_192_964,
              moonrise: 1_654_136_460,
              moonset: 0,
              moon_phase: 0.09,
              temp: {
                day: 295.8,
                min: 288.16,
                max: 296.86,
                night: 292.16,
                eve: 296.09,
                morn: 288.16,
              },
              feels_like: {
                day: 295.17,
                night: 291.81,
                eve: 295.54,
                morn: 287.67,
              },
              pressure: 1021,
              humidity: 40,
              dew_point: 281.54,
              wind_speed: 2.79,
              wind_deg: 181,
              wind_gust: 6.01,
              weather: [
                {
                  id: 802,
                  main: 'Clouds',
                  description: 'переменная облачность',
                  icon: '03d',
                },
              ],
              clouds: 38,
              pop: 0,
              uvi: 6,
            },
            {
              dt: 1_654_246_800,
              sunrise: 1_654_217_496,
              sunset: 1_654_279_441,
              moonrise: 1_654_226_460,
              moonset: 1_654_204_620,
              moon_phase: 0.12,
              temp: {
                day: 287.84,
                min: 287.84,
                max: 294.23,
                night: 289.68,
                eve: 294.23,
                morn: 289.41,
              },
              feels_like: {
                day: 287.85,
                night: 289.03,
                eve: 293.73,
                morn: 289.1,
              },
              pressure: 1019,
              humidity: 95,
              dew_point: 287.03,
              wind_speed: 3.94,
              wind_deg: 221,
              wind_gust: 9.31,
              weather: [
                { id: 501, main: 'Rain', description: 'дождь', icon: '10d' },
              ],
              clouds: 100,
              pop: 0.98,
              rain: 6.99,
              uvi: 6,
            },
            {
              dt: 1_654_333_200,
              sunrise: 1_654_303_841,
              sunset: 1_654_365_915,
              moonrise: 1_654_317_180,
              moonset: 1_654_292_880,
              moon_phase: 0.15,
              temp: {
                day: 293.74,
                min: 285.57,
                max: 294.07,
                night: 289,
                eve: 291.85,
                morn: 286.36,
              },
              feels_like: {
                day: 292.95,
                night: 288.39,
                eve: 291.21,
                morn: 285.75,
              },
              pressure: 1017,
              humidity: 42,
              dew_point: 280.28,
              wind_speed: 3.19,
              wind_deg: 255,
              wind_gust: 9.32,
              weather: [
                {
                  id: 500,
                  main: 'Rain',
                  description: 'небольшой дождь',
                  icon: '10d',
                },
              ],
              clouds: 34,
              pop: 0.46,
              rain: 0.27,
              uvi: 6,
            },
          ],
          alerts: [
            {
              sender_name: '',
              event: 'Thunderstorms',
              start: 1_653_753_600,
              end: 1_653_757_200,
              description: '',
              tags: ['Thunderstorm'],
            },
            {
              sender_name: '',
              event: 'Гроза',
              start: 1_653_753_600,
              end: 1_653_757_200,
              description: 'Местами гроза',
              tags: ['Thunderstorm'],
            },
          ],
        },
      };
      // const getСoordinates = await axios.get(
      //   `https://api.openweathermap.org/data/2.5/onecall?lat=55.750_446_1&lon=37.617_494_3&lang=ru&appid=4ccd5856fcef61a049f819bbe02ae1cc`
      // );
      return { cityy, response: getСoordinates.data };
    } catch {
      return rejectWithValue(null);
    }
  }
);
